version: '3.3'

services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./src:/home/h909220706/socol-taxi.ru/docs
      - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HOST_NGINX_PORT}:${DEFAULT_NGINX_PORT}
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./src:/home/h909220706/socol-taxi.ru/docs
    depends_on:
      - mariadb
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - XDEBUG_CONFIG=remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      - YANDEX_FLEET_PARK_ID=${YANDEX_FLEET_PARK_ID}
      - YANDEX_FLEET_LOGIN=${YANDEX_FLEET_LOGIN}
      - YANDEX_FLEET_PASSWORD=${YANDEX_FLEET_PASSWORD}

  composer:
    build: docker/composer
    volumes:
      - ./src:/home/h909220706/socol-taxi.ru/docs
    working_dir: /home/h909220706/socol-taxi.ru/docs
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - XDEBUG_CONFIG=remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      - YANDEX_FLEET_PARK_ID=${YANDEX_FLEET_PARK_ID}
      - YANDEX_FLEET_LOGIN=${YANDEX_FLEET_LOGIN}
      - YANDEX_FLEET_PASSWORD=${YANDEX_FLEET_PASSWORD}

  php:
    build: docker/php-cli
    volumes:
      - ./src:/home/h909220706/socol-taxi.ru/docs
    working_dir: /home/h909220706/socol-taxi.ru/docs
    depends_on:
      - mariadb
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - XDEBUG_CONFIG=remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      - YANDEX_FLEET_PARK_ID=${YANDEX_FLEET_PARK_ID}
      - YANDEX_FLEET_LOGIN=${YANDEX_FLEET_LOGIN}
      - YANDEX_FLEET_PASSWORD=${YANDEX_FLEET_PASSWORD}

  artisan:
    build: docker/php-cli
    volumes:
      - ./src:/home/h909220706/socol-taxi.ru/docs
    working_dir: /home/h909220706/socol-taxi.ru/docs
    entrypoint:
      - php
      - artisan
    depends_on:
      - mariadb
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - XDEBUG_CONFIG=remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      - YANDEX_FLEET_PARK_ID=${YANDEX_FLEET_PARK_ID}
      - YANDEX_FLEET_LOGIN=${YANDEX_FLEET_LOGIN}
      - YANDEX_FLEET_PASSWORD=${YANDEX_FLEET_PASSWORD}

  serve:
    build: docker/php-cli
    volumes:
      - ./src:/home/h909220706/socol-taxi.ru/docs
    command: php artisan serve
    working_dir: /home/h909220706/socol-taxi.ru/docs
    ports:
      - ${HOST_SERVE_PORT}:${DEFAULT_SERVE_PORT}
    depends_on:
      - mariadb
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - XDEBUG_CONFIG=remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      - YANDEX_FLEET_PARK_ID=${YANDEX_FLEET_PARK_ID}
      - YANDEX_FLEET_LOGIN=${YANDEX_FLEET_LOGIN}
      - YANDEX_FLEET_PASSWORD=${YANDEX_FLEET_PASSWORD}

  tests:
    build: ./docker/tests
    working_dir: /home/h909220706/socol-taxi.ru/docs
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - XDEBUG_CONFIG=remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      - YANDEX_FLEET_PARK_ID=${YANDEX_FLEET_PARK_ID}
      - YANDEX_FLEET_LOGIN=${YANDEX_FLEET_LOGIN}
      - YANDEX_FLEET_PASSWORD=${YANDEX_FLEET_PASSWORD}

    volumes:
      - .:/app
    entrypoint: ./vendor/bin/phpunit --bootstrap vendor/autoload.php
    command: ['tests']
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    volumes:
      - mariadb_volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mariadb_volume: {}
